version: 0.1.2
branches:
  only:
  - master
build_script:
- bin\Prebuild.exe /target vs2010 /targetframework v4_5 /conditionals ISWIN;NET_4_5
- msbuild OpenLife.sln /p:Configuration=Debug  /p:DefineConstants="ISWIN;NET_4_5"
artifacts:
- path: OpenLife\bin
  name: OpenLife
